export const LOAD_MY_MOVIE_LIST = 'LOAD_MY_MOVIE_LIST'
export const MY_MOVIE_LIST_LOADED = 'MY_MOVIE_LIST_LOADED'
export const LOAD_SEARCH = 'LOAD_SEARCH'
export const SEARCH_RESULTS_LOADED = 'SEARCH_RESULTS_LOADED'
